# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homematch', models.CharField(max_length=100)),
                ('awaymatch', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfirstname', models.CharField(max_length=100, verbose_name='Player First Name')),
                ('plastname', models.CharField(max_length=100, verbose_name='Player Last Name')),
                ('pemail', models.EmailField(max_length=254, verbose_name='Player Email')),
                ('mobilenum', models.CharField(max_length=10, verbose_name='Mobile Number')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('rebounds', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Match')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=100, verbose_name='Team Name')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=100, verbose_name='Tournament Name')),
                ('maxteams', models.IntegerField(default=0, verbose_name='Max Teams')),
                ('ttype', models.CharField(max_length=100, verbose_name='Tournament Type')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Tournament'),
        ),
        migrations.AddField(
            model_name='player',
            name='teamname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Tournament'),
        ),
    ]
