# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfirstname', models.CharField(max_length=100, verbose_name='Player First Name')),
                ('plastname', models.CharField(max_length=100, verbose_name='Player Last Name')),
                ('pemail', models.EmailField(max_length=254, verbose_name='Player Email')),
                ('mobilenum', models.CharField(max_length=10, verbose_name='Mobile Number')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=100, verbose_name='Team Name')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='teamname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.Team'),
        ),
    ]
