# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='playernum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='mobilenum',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='player',
            name='pemail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Player Email'),
        ),
    ]
