# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='teamname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Team'),
        ),
    ]
